CREATE TABLE produto
(
    id_produto     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_prod      VARCHAR(255),
    valor_unitario DECIMAL,
    descricao      VARCHAR(255),
    CONSTRAINT pk_produto PRIMARY KEY (id_produto)
);