CREATE TABLE venda
(
    id_venda          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_venda        date,
    valor_total_venda DECIMAL,
    fk_vendedor       BIGINT                                  NOT NULL,
    CONSTRAINT pk_venda PRIMARY KEY (id_venda)
);

ALTER TABLE venda
    ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (fk_vendedor) REFERENCES vendedor (id_vendedor);