CREATE TABLE item_venda
(
    id_item     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade  INT                                     NOT NULL,
    produto_id  BIGINT                                  NOT NULL,
    preco_venda DECIMAL(10, 2)                          NOT NULL,
    venda_id    BIGINT,
    CONSTRAINT pk_item_venda PRIMARY KEY (id_item)
);

ALTER TABLE item_venda
    ADD CONSTRAINT FK_ITEM_VENDA_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produto (id_produto);

ALTER TABLE item_venda
    ADD CONSTRAINT FK_ITEM_VENDA_ON_VENDA FOREIGN KEY (venda_id) REFERENCES venda (id_venda);